version: '3.11'
services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_db
    volumes:
       - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  api: 
    build: 
      context: .
    command: "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./src:/app
    environment:      
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '8000:8000'
    depends_on: 
      - postgres